### ISSUE TITLE
Unable to pull any values/data from the 2 online cameras

### ISSUE THREAD

**Issue by johnforfar** [jtsiros/nest#2]
It doesn't appear that the device ID's are making there way to the Cameras function, as it keeps returning null data from the Nest API. Therefore the Is Streaming is always false, even though it is most definitelty online. As you can see, the sanitised device Id's are coming through, as the n.Devices shows I have no thermostats, smoke alarms, but 2 cameras. I'm new to Go, so struggling to pass the ID manually into the struct>map>data array. Any ideas? Any good test code, that can be run from the main.go file that is specific to camera testing? Thanks

fmt.Println(n.Devices())
> &{map[] map[] map[1abcde-abcdefghijklmnopqrstuvwxyz:0x12345678 k--2abcde-abcdefghijklmnopqrstuvwxyz:0x123456789]} <nil>

camera, err := n.Cameras.Get("[DEVICE_ID]")
fmt.Println(camera)
> &{       false false false 0001-01-01 00:00:00 +0000 UTC false   false []  }

fmt.Println(camera.IsStreaming)
> false

**Comment by johnforfar** [comment]
Sorry to keep pushing on this. Nearly there I think, but it is this one last error. n.Devices returns multiple-values from a function and no matter what code I try I cannot unpack the values from the map. Any ideas?

```
for deviceID, device := range n.Devices() {
	fmt.Printf("device id: %s - device: %+v\n", deviceID, device)
}
```
error: multiple-value n.Devices() in single-value context
==============================================================
```
> devicelist, _ := n.Devices()
> for deviceID, device := range devicelist {
> 	fmt.Printf("device id: %s - device: %+v\n", deviceID, device)
> }
```
error: cannot range over devicelist (type *device.Devices)

**Comment by jtsiros** [comment]
> orry to keep pushing on this. Nearly there I think, but it is this one last error. n.Devices returns multiple-values from a function and no matter what code I try I cannot unpack the values from the map. In terms of the Cameras.Get I managed to get this to work by _ the error value, however it still outputs empty values. Any ideas?
> 
> ```
> for deviceID, device := range n.Devices() {
> 	fmt.Printf("device id: %s - device: %+v\n", deviceID, device)
> }
> ```

sorry, I forgot to add `n.Devices().Cameras()`. That should get you the map of cameras.

**Comment by jtsiros** [comment]
Also, just so you are aware, the Nest API does not let you capture the raw camera stream. The stream REST api lets you stream for changes to the device itself. You'll have to redirect to either the `web_url` or the `app_url` to view the actual stream.

```
jbumgardner Staff Nov '17
Ah ok, I understand what you’re trying to do now, thanks for the clarification.

Unfortunately there’s no way to directly stream the live camera feed 
within a non-Nest application using the Nest API. You have to 
redirect the user to one of the two browser options as you described 
(public_share_url or web_url).
```
https://nestdevelopers.io/t/streaming-from-indoor-outdoor-cams/1074/6
https://developers.nest.com/guides/api/rest-streaming-guide
https://developers.nest.com/reference/api-camera

**Comment by johnforfar** [comment]
> for deviceID, device := range n.Devices() {
> 	fmt.Printf("device id: %s - device: %+v\n", deviceID, device)
> }
this returns a "**multiple-value n.Devices() in single-value context**"

> cameralist := n.Devices().Cameras
> 	fmt.Println(cameralist)
this returns a "**multiple-value n.Devices() in single-value context**"

I keep getting the above errors, unfortunately my knowledge of Go functions, arrays, slices is not up to the task of getting this working. Any help appreciated.

**Comment by jtsiros** [comment]
> cameralist := n.Devices().Cameras
> fmt.Println(cameralist)
> this returns a "**multiple-value n.Devices() in single-value context**"

`n.Devices().Cameras` returns a map (two values) with a key and value. You'll need something like this:

```go
deviceID, camera := range n.Devices().Cameras {
    fmt.Printf("id: %s - %+v\n", deviceID, camera)
}
```

You can look at [devices.go](https://github.com/jtsiros/nest/blob/master/device/devices.go#L9) on what `Devices()` and `Devices().Cameras` returns.

**Comment by johnforfar** [comment]
Hurrah! This is the code that eventually worked perfectly. Thanks for the help

```
cameraID, _ := n.Devices()
	for deviceID, camera := range cameraID.Cameras {
		fmt.Println("\n Camera Object ID: %s", deviceID)
		fmt.Println("\n Camera Data: %+v", camera)
	}
```
